---
stages:
  - lint
  - build
  - sanitize
  - coverage

clang-format:
  stage: lint
  tags:
    - mc-linux-slow
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - cd $CI_PROJECT_DIR
    - make format-check
  dependencies: [ ]

win:msvc:release:
  stage: build
  tags:
    - mc-windows
  variables:
    ErrorActionPreference: stop
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_STRATEGY: clone
  script:
    - Set-Location $env:CI_PROJECT_DIR
    - New-Item -Path cmake-build-release -ItemType Directory
    - Set-Location cmake-build-release
    - cmake -S ..
    - if(!$?) { Write-Host "Failed" } else { Write-Host "Success" }
    - cmake --build . --config Release
    - if(!$?) { Write-Host "Failed" } else { Write-Host "Success" }
    - ctest
    - if(!$?) { Write-Host "Failed" } else { Write-Host "Success" }
    - Set-Location $env:CI_PROJECT_DIR
  dependencies: [ ]

mac:xcode:release:
  stage: build
  tags:
    - mc-macos
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - cd $CI_PROJECT_DIR
    - cmake -S. -GNinja -Bcmake-build-release -DCMAKE_BUILD_TYPE=Release -DMODERN_CIRCUITS_BUILD_WERROR=ON
    - cmake --build cmake-build-release
    - cd cmake-build-release
    - ctest
    - cd $CI_PROJECT_DIR
  dependencies: [ ]

linux:clang:release:
  stage: build
  tags:
    - mc-linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CC: clang-12
    CXX: clang++-12
  script:
    - cd $CI_PROJECT_DIR
    - cmake -S. -GNinja -Bcmake-build-release -DCMAKE_BUILD_TYPE=Release -DMODERN_CIRCUITS_BUILD_WERROR=ON
    - cmake --build cmake-build-release
    - cd cmake-build-release
    - ctest
    - cd $CI_PROJECT_DIR
  dependencies: [ ]

linux:clang-tidy:
  stage: build
  tags:
    - mc-linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - cd $CI_PROJECT_DIR
    - cmake -S. -GNinja -Bcmake-build-tidy -DCMAKE_BUILD_TYPE=Release
    - BUILD_DIR=cmake-build-tidy make tidy-check
  dependencies: [ ]

linux:gcc:asan:
  stage: sanitize
  tags:
    - mc-linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - cd $CI_PROJECT_DIR
    - cmake -S. -GNinja -Bcmake-build-asan -DCMAKE_BUILD_TYPE=Release -DMODERN_CIRCUITS_BUILD_ASAN=ON
    - cmake --build cmake-build-asan
    - cd cmake-build-asan
    - ctest
    - cd $CI_PROJECT_DIR
  dependencies: [ ]

linux:gcc:tsan:
  stage: sanitize
  tags:
    - mc-linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - cd $CI_PROJECT_DIR
    - cmake -S. -GNinja -Bcmake-build-tsan -DCMAKE_BUILD_TYPE=Release -DMODERN_CIRCUITS_BUILD_TSAN=ON
    - cmake --build cmake-build-tsan
    - cd cmake-build-tsan
    - ctest
    - cd $CI_PROJECT_DIR
  dependencies: [ ]

linux:gcc:coverage:
  stage: coverage
  only:
    - main
  tags:
    - mc-linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - make coverage
    - bash <(curl -s https://codecov.io/bash) -f cmake-build-coverage/cov.info
    - find . -type f -executable -iname "*_Test*" -exec sh -c "{} -r junit -o {}-results.xml" \;
  dependencies: [ ]
  artifacts:
    when: always
    reports:
      junit: cmake-build-coverage/**/*-results.xml