name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux:
    name: Linux
    strategy:
      matrix:
        cxx: [14, 17, 20]
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true

      - name: Install conan
        run: |
          sudo apt update -y
          pip install conan
          conan config set general.revisions_enabled=1

      - name: Install JUCE dependencies
        run: >
          sudo apt install -y
          ninja-build
          gcovr
          lcov
          libasound2-dev
          libjack-jackd2-dev
          ladspa-sdk
          libcurl4-openssl-dev
          libfreetype6-dev
          libx11-dev
          libxcomposite-dev
          libxcursor-dev
          libxcursor-dev
          libxext-dev
          libxinerama-dev
          libxrandr-dev
          libxrender-dev
          libwebkit2gtk-4.0-dev
          libglu1-mesa-dev
          mesa-common-dev

      - name: Run coverage build
        run: CXX_STD="${{ matrix.cxx }}" make coverage-xml

      - uses: codecov/codecov-action@v3
        with:
          files: ./cmake-build-coverage/coverage.xml
          fail_ci_if_error: true
