name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        cxx: [14, 17, 20]
        build_mode: ["Debug", "Release"]
      fail-fast: false
    name: ${{ matrix.cxx }} - ${{ matrix.build_mode }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true

      - name: Install dependencies
        run: |
          pip install conan
          conan config set general.revisions_enabled=1

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: CMake configure
        run: >
          cmake
          -S .
          -G "Visual Studio 17 2022"
          -B build
          -D CMAKE_BUILD_TYPE=${{ matrix.build_mode }}
          -D CMAKE_CXX_STANDARD="${{ matrix.cxx }}"
          -D MC_BUILD_WERROR=ON

      - name: CMake build
        run: cmake --build build --config ${{ matrix.build_mode }}

      - name: CTest
        run: ctest --test-dir build -C ${{ matrix.build_mode }} --output-on-failure
