name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  DISPLAY: :0
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-22.04
          - name: macOS-X64
            os: macos-13
          - name: Windows
            os: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update -y
          sudo apt install -y libasound2-dev libx11-dev libxrandr-dev libxinerama-dev libxext-dev libfreetype6-dev libglu1-mesa-dev xvfb ninja-build

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install ninja

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: choco install ninja ccache

      - name: Install conan
        run: |
          pip3 install --force-reinstall -v "conan==1.59.0"
          conan config init
          conan config set general.revisions_enabled=1

      - name: Install ccache
        if: ${{ matrix.name != 'macOS-ARM64' }}
        uses: hendrikmuhs/ccache-action@main
        with:
          key: v3-${{ matrix.name }}-Debug

      - name: CMake configure
        shell: bash
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug

      - name: CMake build
        shell: bash
        run: cmake --build build --config Debug --target all

      - name: CTest
        shell: bash
        run: ctest --test-dir build -C Debug --output-on-failure
