name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cxx: [14, 17, 20]
      fail-fast: false
    name: Linux C++ ${{ matrix.cxx_std }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true

      - name: Install JUCE dependencies
        run: >
          sudo apt install -y
          ninja-build
          libasound2-dev
          libjack-jackd2-dev
          ladspa-sdk
          libcurl4-openssl-dev
          libfreetype6-dev
          libx11-dev
          libxcomposite-dev
          libxcursor-dev
          libxcursor-dev
          libxext-dev
          libxinerama-dev
          libxrandr-dev
          libxrender-dev
          libwebkit2gtk-4.0-dev
          libglu1-mesa-dev
          mesa-common-dev

      - name: Install conan
        run: |
          pip install conan
          conan config set general.revisions_enabled=1

      - name: CMake configure -- Debug
        run: cmake -S . -G Ninja -B cmake-build-debug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD="${{ matrix.cxx_std }}"

      - name: CMake build -- Debug
        run: cmake --build cmake-build-debug

      - name: CTest -- Debug
        run: ctest --test-dir cmake-build-debug -C Debug

      - name: CMake configure -- Release
        run: cmake -S . -G Ninja -B cmake-build-release -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD="${{ matrix.cxx_std }}"

      - name: CMake build -- Release
        run: cmake --build cmake-build-release

      - name: CTest -- Release
        run: ctest --test-dir cmake-build-release -C Release
