name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        cxx: [14, 17, 20]
      fail-fast: false
    name: Windows C++ ${{ matrix.cxx_std }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true

      - name: Install dependencies
        run: |
          pip install conan
          conan config set general.revisions_enabled=1

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: CMake configure -- Debug
        run: cmake -S . -B cmake-build-debug -G "Visual Studio 17 2022" -D CMAKE_BUILD_TYPE=Debug

      - name: CMake build -- Debug
        run: cmake --build cmake-build-debug --config "Debug"

      - name: CTest -- Debug
        run: ctest --test-dir cmake-build-debug -C Debug

      - name: CMake configure -- Release
        run: cmake -S . -B cmake-build-release -G "Visual Studio 17 2022" -D CMAKE_BUILD_TYPE=Release

      - name: CMake build -- Release
        run: cmake --build cmake-build-release --config "Release"

      - name: CTest -- Release
        run: ctest --test-dir cmake-build-release -C Release
